# Generated by Django 3.2.14 on 2022-07-19 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=100)),
                ('item_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
