# Generated by Django 3.2.14 on 2022-07-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
